### ISSUE TITLE
No line numbers or scroll bars shown

### ISSUE THREAD

**Issue by oscarmcm** [sk1p/django-codemirror2#8]
I want to use CodeMirror2 in a Admin ModelForm, but the scroll bar and line number not appear, only load the text. Any idea?

![image](https://cloud.githubusercontent.com/assets/2553459/12902661/1f8b39b0-ce88-11e5-84f8-69308eeffd72.png)

**Comment by sk1p** [comment]
Line numbers are disabled by default, you can enable them by passing the ``lineNumbers`` option to your widget, for example like this:

```
class SomeModelForm(forms.ModelForm):
    class Meta:
        model = SomeModel
        widgets = {'yourfield': CodeMirrorEditor(options={'lineNumbers': True})}
```

As for scroll bars, they should appear once you fill the editor, see the following image:

![scroll bars and line numbers](https://cloud.githubusercontent.com/assets/5778/12907911/59a1300a-cef1-11e5-8293-963fd03ebab7.png)

As there does not appear to be a problem with the Django integration of codemirror, I'm closing this issue.
